### ISSUE TITLE
Refactor code with hooks

### ISSUE THREAD

**Issue by Uthmanbello** [Uthmanbello/math-magicians#6]
## Importation of object and hook
https://github.com/Uthmanbello/math-magicians/blob/9976598e419d2d001ac4568052982600bce51138/src/components/Calculator.js#L2
-  This line imports React object and the `useState` hook from the React library. 
- The `useState` hook allows us to define state variables in functional components.

## Definition of function
https://github.com/Uthmanbello/math-magicians/blob/9976598e419d2d001ac4568052982600bce51138/src/components/Calculator.js#L5
- At the line above, the functional component was defined

## Declaration of initial state
https://github.com/Uthmanbello/math-magicians/blob/9976598e419d2d001ac4568052982600bce51138/src/components/Calculator.js#L6-L10
- These lines declare a new state variable named `calculation` using the `useState` hook. 
- The initial state of this variable is an object with three properties - `total`, `next`, and `operation` - all set to null. 
- The `setCalculation` function is used to update the value of `calculation`.

## Implementation of update of initial state
https://github.com/Uthmanbello/math-magicians/blob/9976598e419d2d001ac4568052982600bce51138/src/components/Calculator.js#L12-L14
- These lines define a function named `handleClick` that takes in a `buttonName` argument. 
- This function uses the `setCalculation` function to update the value of `calculation` using the `calculate` module imported earlier, passing in the current `calculation` and the `buttonName` as arguments.

**Comment by Favourezeugwa** [comment]
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @Uthmanbello ,

I am Favour 👩🏽 , your reviewer for this project milestone.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

![happy](https://user-images.githubusercontent.com/99246359/202491301-53f8c6a2-8ff4-4337-9b6b-9c75c8bdf345.gif)

## Highlights 💯 
- No Linter errors ✔️
- Functional component used ✔️
- Gitflow used ✔️
- Descriptive Issue comments ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
